### ISSUE TITLE
Blocking/Timeouts

### ISSUE THREAD

**Issue by mwang87** [mikeckennedy/umami-python#10]
This is a great project @mikeckennedy. 

Are any of the calls to an umami server blocking with a timeout? Just curious if it would be better for me when integrating into an application, to move all these calls into an asychronous portion of the code to prevent sychronous web apis to hang in case the umami server is slow.

**Comment by mikeckennedy** [comment]
Hi @mwang87 Thank you! No need to worry about them. Every network-based action has both a sync and async version of the API. For example, for logging in (not needed for posting events/views btw), you have:

- `def login(username: str, password: str) -> models.LoginResponse:`
- `async def login_async(username: str, password: str) -> models.LoginResponse:`

We use `httpx` underneath for this and their timeout policy is "The default behavior is to raise a TimeoutException after 5 seconds of network inactivity."
