### ISSUE TITLE
Support IP address in new_event and new_page_view payloads

### ISSUE THREAD

**Issue by ddxv** [mikeckennedy/umami-python#2]
There is a potential PR for Umami to support adding an IP address to the payload for server side applications to forward the IP address. Obviously this would be perfect for this project, so looking forward to this going through:

https://github.com/umami-software/umami/pull/2479

**Comment by mikeckennedy** [comment]
Thanks! That would be excellent. I'm "watching" that PR and once it gets through and is published, I'll add that to this library too.

**Comment by mikeckennedy** [comment]
It looks like Umami added the IP data field in the payload (see https://github.com/umami-software/umami/pull/2479 ). It's not clear when the feature will be released in a new build ( https://github.com/umami-software/umami/releases ). But in preparation, I added the `id_address` parameter to both `new_event` and `new_page_view` as well as their async twins.

This is out in version 0.1.13 and on PyPI at https://pypi.org/project/umami-analytics/0.1.13/ Thanks for the idea @ddxv

**Comment by ddxv** [comment]
Great, pretty excited to use this.

**Comment by mikeckennedy** [comment]
Glad to hear it! You can start using the IP in the client already. I don't think it'll have any effect until Umami releases its next version but it doesn't seem to cause a problem in the event processing with the current version (for example, extra data in the payload doesn't crash the request as a 400 bad request or anything like that).

**Comment by ddxv** [comment]
> Glad to hear it! You can start using the IP in the client already. I don't think it'll have any effect until Umami releases its next version but it doesn't seem to cause a problem in the event processing with the current version (for example, extra data in the payload doesn't crash the request as a 400 bad request or anything like that).

This has recently been released by Umami and I can confirm the issue is fixed and its working now. In my use case the UA is still all the same, so it appears as one set of os/browser etc but you can see the countries and individual users looks much more realistic:

![image](https://github.com/mikeckennedy/umami-python/assets/7601451/ce89bd5b-ba7b-4d3e-8cbf-6e75834c356f)

**Comment by mikeckennedy** [comment]
Very nice, and thanks a bunch for following up on this. This was released as part of 2.10, right?
